const fs=require('fs');
let p=fs.readFileSync('src/app/page.tsx','utf8');
let lines=p.split('\n');

// Encontrar donde empieza y termina HeroSection
var start=-1,end=-1;
for(var i=0;i<lines.length;i++){
  if(lines[i].includes('function HeroSection()')){start=i;}
  if(start>-1&&end===-1&&i>start+5&&lines[i].trim()==='}'&&lines[i-1].trim()!==''){end=i;}
}
console.log('HeroSection: L'+(start+1)+' a L'+(end+1));

// Construir nuevo HeroSection
var hero=[
  '/* --- HERO --- */',
  'function HeroSection() {',
  '  const { scrollYProgress } = useScroll();',
  '  const heroOpacity = useTransform(scrollYProgress, [0, 0.15], [1, 0.4]);',
  '  const [isMob, setIsMob] = useState(false);',
  '  useEffect(() => { setIsMob(window.innerWidth < 768); const fn = () => setIsMob(window.innerWidth < 768); window.addEventListener("resize", fn); return () => window.removeEventListener("resize", fn); }, []);',
  '',
  '  const ease = [0.4, 0, 0.2, 1];',
  '',
  '  return (',
  '    <section',
  '      style={{',
  '        position: "relative",',
  '        background: "#0A0F1E",',
  '        minHeight: "100vh",',
  '        display: "flex",',
  '        flexDirection: "column",',
  '        justifyContent: "center",',
  '        overflow: "hidden",',
  '        paddingTop: "140px",',
  '        paddingBottom: "140px",',
  '      }}',
  '    >',
  '',
  '      <div style={{ position: "absolute", inset: 0, opacity: 0.35 }}>',
  '        <GoldParticleChart />',
  '      </div>',
  '',
  '      <motion.div',
  '        style={{',
  '          position: "relative",',
  '          zIndex: 1,',
  '          maxWidth: 640,',
  '          margin: isMob ? "0 auto" : "0",',
  '          padding: isMob ? "8rem 1.5rem 4rem" : "8rem 2rem 4rem",',
  '          textAlign: isMob ? "center" : "left",',
  '          opacity: heroOpacity,',
  '        }}',
  '      >',
  '',
  '        {/* Eyebrow */}',
  '        <motion.p',
  '          initial={{ opacity: 0, y: 16 }}',
  '          animate={{ opacity: 1, y: 0 }}',
  '          transition={{ duration: 0.6, delay: 0, ease: ease }}',
  '          style={{',
  '            fontFamily: "var(--font-jost)",',
  '            fontSize: 11,',
  '            letterSpacing: "4px",',
  '            textTransform: "uppercase" as const,',
  '            color: "#4A7CF7",',
  '            marginBottom: 16,',
  '          }}',
  '        >',
  '          — Carolina Betancourt',
  '        </motion.p>',
  '',
  '        {/* Headline */}',
  '        <motion.h1',
  '          initial={{ opacity: 0, y: 18 }}',
  '          animate={{ opacity: 1, y: 0 }}',
  '          transition={{ duration: 0.6, delay: 0.1, ease: ease }}',
  '          style={{',
  '            fontFamily: "var(--font-cormorant)",',
  '            fontWeight: 300,',
  '            fontSize: isMob ? 38 : 62,',
  '            lineHeight: 1.05,',
  '            color: "#FFFFFF",',
  '            marginBottom: 24,',
  '          }}',
  '        >',
  '          La mayoria de agencias optimiza anuncios.<br/>',
  '          Yo optimizo lo que te cuesta <span style={{ color: "#4A7CF7" }}>cada venta</span>.',
  '        </motion.h1>',
  '',
  '        {/* Subheadline */}',
  '        <motion.p',
  '          initial={{ opacity: 0, y: 18 }}',
  '          animate={{ opacity: 1, y: 0 }}',
  '          transition={{ duration: 0.6, delay: 0.25, ease: ease }}',
  '          style={{',
  '            fontFamily: "var(--font-jost)",',
  '            fontWeight: 300,',
  '            fontSize: 16,',
  '            color: "rgba(255,255,255,0.68)",',
  '            maxWidth: 560,',
  '            lineHeight: 1.85,',
  '            marginBottom: 36,',
  '            marginLeft: isMob ? "auto" : undefined,',
  '            marginRight: isMob ? "auto" : undefined,',
  '          }}',
  '        >',
  '          Trabajo con negocios que ya invierten en Meta Ads y saben que algo no esta funcionando — aunque todavia no logran identificar exactamente que esta frenando el rendimiento.',
  '          <br/><br/>',
  '          Ahi es donde entro yo.',
  '        </motion.p>',
  '',
  '        {/* CTAs */}',
  '        <motion.div',
  '          initial={{ opacity: 0, y: 18 }}',
  '          animate={{ opacity: 1, y: 0 }}',
  '          transition={{ duration: 0.6, delay: 0.4, ease: ease }}',
  '          style={{',
  '            display: "flex",',
  '            flexDirection: isMob ? "column" : "row",',
  '            gap: 14,',
  '            marginBottom: 20,',
  '            justifyContent: isMob ? "center" : "flex-start",',
  '          }}',
  '        >',
  '          <a',
  '            href="https://wa.me/522292924043"',
  '            style={{',
  '              display: "inline-block",',
  '              background: "#4A7CF7",',
  '              color: "#FFFFFF",',
  '              fontFamily: "var(--font-jost)",',
  '              fontWeight: 500,',
  '              fontSize: "0.85rem",',
  '              padding: "14px 28px",',
  '              borderRadius: 10,',
  '              textDecoration: "none",',
  '              letterSpacing: "0.04em",',
  '              transition: "all 0.25s",',
  '              textAlign: "center",',
  '            }}',
  '            onMouseEnter={function(e){e.currentTarget.style.background="#3a6ce6";e.currentTarget.style.transform="translateY(-1px)";}}',
  '            onMouseLeave={function(e){e.currentTarget.style.background="#4A7CF7";e.currentTarget.style.transform="none";}}',
  '          >',
  '            Quiero saber que esta fallando',
  '          </a>',
  '          <a',
  '            href="#sistema-filtro"',
  '            style={{',
  '              display: "inline-block",',
  '              background: "transparent",',
  '              border: "1px solid rgba(255,255,255,0.3)",',
  '              color: "#FFFFFF",',
  '              fontFamily: "var(--font-jost)",',
  '              fontWeight: 500,',
  '              fontSize: "0.85rem",',
  '              padding: "14px 28px",',
  '              borderRadius: 10,',
  '              textDecoration: "none",',
  '              letterSpacing: "0.04em",',
  '              transition: "all 0.25s",',
  '              textAlign: "center",',
  '            }}',
  '            onMouseEnter={function(e){e.currentTarget.style.borderColor="rgba(255,255,255,0.6)";}}',
  '            onMouseLeave={function(e){e.currentTarget.style.borderColor="rgba(255,255,255,0.3)";}}',
  '          >',
  '            Ver el Metodo P.U.L.S.O.',
  '          </a>',
  '        </motion.div>',
  '',
  '        {/* Trust line */}',
  '        <motion.p',
  '          initial={{ opacity: 0, y: 14 }}',
  '          animate={{ opacity: 1, y: 0 }}',
  '          transition={{ duration: 0.6, delay: 0.55, ease: ease }}',
  '          style={{',
  '            fontFamily: "var(--font-jost)",',
  '            fontSize: 11,',
  '            letterSpacing: "2px",',
  '            textTransform: "uppercase" as const,',
  '            color: "rgba(255,255,255,0.38)",',
  '          }}',
  '        >',
  '          Sin contratos forzosos · Optimizacion basada en datos reales · CPA documentado: -52% en 5 ciclos',
  '        </motion.p>',
  '',
  '      </motion.div>',
  '    </section>',
  '  );',
  '}',
];

lines.splice(start,end-start+1,...hero);
fs.writeFileSync('src/app/page.tsx',lines.join('\n'),'utf8');
console.log('HeroSection reemplazada! ('+hero.length+' lineas nuevas)');
